import * as Factory from 'factory.ts'

export const LoadsModelFactory = Factory.makeFactory<{[key: string]: any}>({
     batchSequence: null,
     createdBy: "haarish",
     deletedBy: null,
     loadId: 25121476,
     loadNumber: "test13",
     originalScac: "T1105393",
     proNumber: null,
     priority: "normal",
     version: 2,
     referenceNumbers: [],
     deleted: false,
     deletedAt: null,
     demoLoad: false,
     customer: {},
     id: 310983,
     numberOfDeliveryStops: 1,
     stops: [],
     products: null,
     temperatureTrackingStarted: null,
     status: "Picked Up",
     originStopId: 61001930,
     origin: "Chicago, IL",
     originAddress: "136 N La Salle St, Chicago, IL, US",
     originTimeZoneOffset: -18000,
     originTimeZoneName: "CDT",
     originAppointmentTime: "2018-08-28T15:05:00Z",
     originEarliestAppointmentTime: "2018-08-28T14:25:00Z",
     originLatestAppointmentTime: "2018-08-28T15:05:00Z",
     destinationStopId: 61001931,
     destination: "Washington, DC",
     destinationAddress: "14th St NW, Washington, DC, US",
     destinationAppointmentTime: "2018-08-29T12:10:00Z",
     destinationEarliestAppointmentTime: "2018-08-29T11:10:00Z",
     destinationLatestAppointmentTime: "2018-08-29T12:10:00Z",
     destinationTimeZoneOffset: -18000,
     destinationTimeZoneName: "CDT",
     destinationCalculatedAppointmentTime: null,
     totalDistance: 1152035,
     currentHos: 1147,
     currentElapsedRestTime: 0,
     restingSince: null,
     lastComputedCheckCallId: 869725,
     progressPercentage: 97,
     canUpdateStops: true,
     canDeleteLoad: true,
     canUpdateLoad: true,
     canUpdateTrackingInfo: true,
     canCompleteStops: true,
     missingTrackingInfoAlertSent: false,
     excludeFromAnalytics: false,
     stopTracking: false,
     relayLoad: false,
     forceStart: null,
     loadMode: "truck",
     testLoad: false,
     onboardingStatus: "live",
     haulParameters: [],
     trackingStrategy: "sequential",
     showMap: true,
     trackingMethod: "Other",
     terminatedAt: null,
     billingType: null,
     latestHeadingAngle: 77.4867226238929,
     trackingNumber: null,
     selfAssignPinNumber: null,
     shipper: {
       id: "unilever",
       name: "Unilever",
       loadUpdatesEnabled: false,
       stopLevelView: "fullView",
       showLatestLocationInStopLevel: null
     },
     carrier: {
       id: "frachtfwo",
       name: "Frachtfwo",
       loadUpdatesEnabled: false,
       railTrackingMode: null,
       holdTimeInMinutes: 1440
     },
     managingCarrier: {
       id: "frachtfwo",
       name: "Frachtfwo",
       loadUpdatesEnabled: false,
       railTrackingMode: null,
       holdTimeInMinutes: 1440
     },
     operatingCarrier: {
       id: "frachtfwo",
       name: "Frachtfwo",
       loadUpdatesEnabled: false,
       railTrackingMode: null,
       holdTimeInMinutes: 1440
     },
     "3pl": {
       id: null,
       name: null
     },
     crossDockLoad: false,
     lessThanTruckLoad: false,
     modes: [
       "TL"
     ],
     encryptedAccessToken: "VjJ8dW5pbGV2ZXJ8MmVhOTU2ZWUtYTBkYi00MThkLTg3N2ItNzhhNzM4YWUxZWVl",
     delayBufferInMinutes: 30,
     sequencingLogic: "strict",
     mobileTracking: false,
     useMobileTracking: false,
     recentMessages: [],
     lateReasonCodes: [],
     tags: [],
     truckNumber: null,
     trailerNumber: null,
     driverPhone: null,
     deviceId: null,
     dispatcherEmail: null,
     railEquipmentInitials: null,
     railEquipmentNumber: null,
     vesselName: null,
     imo: null,
     mmsi: null,
     containerNumber: null,
     completeDriverPhone: null,
     messagesCount: 0,
     latestCheckCallId: 869725,
     latestCheckCallAt: "2018-08-30T04:27:14.698Z",
     firstCheckCallId: 869721,
     firstCheckCallAt: "2018-08-30T04:18:56Z",
     firstLocationPingAt: null,
     timeZoneOffset: -18000,
     timeZoneName: "CDT",
     createdAt: "2018-08-30T03:10:56Z",
     updatedAt: "2018-08-30T08:51:35Z",
     pickupCheckCallId: 869721,
     pickupCheckCallAt: "2018-08-30T04:18:56.088Z",
     deliveryCheckCallId: null,
     deliveryCheckCallAt: null,
     remainingDistance: 32870,
     trackingStatus: {
       latestLocation: {
         id: 869725,
         name:  "Ping5",
         latitude: 38.8658,
         longitude: -76.8471,
         city: "",
         state: "",
         country: "US",
         headingAngle: 77.4867226238929,
         timestamp: "2018-08-30T04:27:14Z",
         locatedAt: "2018-08-30T04:27:14Z",
         timeZoneOffset: -18000,
         timeZoneName: "CDT",
         mode: "truck",
         event: null,
         loadMode: "truck",
         lastCheckCallTimeFromNow: 271,
         additionalData: null,
         provider: null
       },
       deliverySchedule: {
         timeUntilPlannedDeliveryInMinutes: -429,
         timeUntilPlannedDeliveryInMinutesForWantTime: null,
         timeUntilActualDeliveryInMinutes: null,
         timeUntilEstimatedDeliveryInMinutes: -437,
         nextStopETA: "2018-08-30T05:01:04.000Z",
         nextDeliveryStopMode: "truck",
         timeZoneName: "EDT",
         timeZoneOffset: -14400
       },
       autoEtaTriggered: false
     },
     pickedUp: true,
     parentLoadNumber: null,
     canGetDeviceLocation: false,
     canSubscribeDevice: false,
     realTimeNotification: {
       channel: "fk-ld-310983"
     },
     truckRoutingParams: {},
     receivedLocationsForLoad: true,
     shipperReferenceNumber: null,
     operatingCarrierScac: null,
     atRisk: true,
     atRiskReasons: [
       "ETA is more than 1 hour after the scheduled delivery time.",
       "We have not received updates on this load from the carrier for over 4 hours. ETA is now over 4 hours old.",
       "Stale location"
     ],
     atRiskShortReasons: [
       {
         reason: "delivery_at_risk",
         timestamp: "2018-08-30T04:19:14.719Z"
       },
       {
         reason: "location_file_no_recent_updates",
         timestamp: "2018-08-30T06:36:09Z"
       },
       {
         reason: "stale_location",
         timestamp: "2018-08-30T06:36:09Z"
       }
     ],
     linkedLoadId: null,
     nonBillable: false,
     linkedLoadEtaEnabled: null,
     pickupAppointmentRange: "2018-08-28T14:25:00Z/2018-08-28T15:05:00Z",
     deliveryAppointmentRange: "2018-08-29T10:10:00Z/2018-08-29T11:10:00Z",
     dwellTimeStatus: {
       geofenceStatus: "on_route",
       dwellTimeStart: "2018-08-30T04:27:14.000Z",
       dwellTimeEnd: "2018-08-30T04:27:14.000Z",
       distanceTravelledInMetresDuringDwell: 0,
       lastCheckCallProcessedId: 869725,
       latitude: 38.8658,
       longitude: -76.8471,
       location:  "Ping5",
       stopId: null
     },
     headrunProcessedId: null,
     appointmentRange: "2018-08-28T14:25:00Z/2018-08-29T11:10:00Z",
     isETAPushedDueToBusinessHours: false,
     liveDwellStartAt: null,
     carrierReferenceNumbers: null,
     primaryReferenceNumber: "test13",
     serviceLevel: null,
     deliveryType: null,
     masterSequenceNumber: null,
     masterReferenceNumber: null
   }
 )

export const TemperatureLoadFactory = LoadsModelFactory.extend({
  products: [{"name":"test","productId":53,"externalId":"ice","setTemperature":10.0,"timeToleranceInMinutes":2,"status":"warning","lowerTemperatureThreshold":9.0,"upperTemperatureThreshold":15.0,"temperatureUnit":"F","last_check_call_processed_time":"2018-09-18T06:14:19.000+00:00","violation_start_time":"2018-09-18T06:14:19.000+00:00","violation_end_time":"2018-09-18T06:14:19.000+00:00"}]
})
